swagger: '2.0'
info:
  title: Cloud Endpoints
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: hello-world-ypvsiifxxa-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://cloudrun-srv2-ypvsiifxxa-uc.a.run.app
  protocol: h2
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string
