Palanikumar M 30-05-2024 10:20 • name: Terraform CI Pipeline

on:
push:
branches:
- main

jobs:
terraform:
runs-on: ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v2

- name: Set up Terraform
uses: hashicorp/setup-terraform@v2
with:
terraform_version: 1.3.0 # Use the required Terraform version

- name: Install tflint
run: |
curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

- name: Terraform Format Check
run: terraform fmt -check

- name: Terraform Lint Check
run: tflint --config .tflint.hcl

- name: Terraform Validate
run: terraform validate
